version: "3.8"
services: 
  api:
    build: .
    container_name: final
    ports:
      - '4000:4000'
    volumes:
      - /app/node_modules
  frontend:
    build: . 
    container_name: frontend_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true